/**
 * @file catalogCsvDomain.ts
 * @description CSV import/export for the shared Catalog contract used by the
 * Business OS and Storefront. The import accepts the legacy five-column file
 * as well as the richer customer-facing fields introduced by the Storefront
 * catalog (occasions, arrangement type, collection, pricing type, order type).
 * Product ID and SKU are used only to match existing records; identifiers for
 * newly-created products/variants are still generated by the Catalog store.
 */

import type {
  CatalogCategory,
  CatalogMaterial,
  CatalogProduct,
  CatalogVariantStatus,
} from '../store/catalogStoreTypes'

const CSV_IMPORT_COLUMNS = [
  'Product ID',
  'SKU',
  'Product Name',
  'Category',
  'Occasion Tags',
  'Arrangement Type',
  'Size',
  'Material Type',
  'Collection / Series',
  'Price',
  'Cost',
  'Pricing Type',
  'Order Type',
  'Variant Status',
  'Product Active',
  'Featured',
  'Customizable',
  'Description',
] as const

export type CatalogCsvOptionalField =
  | 'productId'
  | 'sku'
  | 'occasionTags'
  | 'productType'
  | 'collectionSeries'
  | 'cost'
  | 'pricingType'
  | 'orderType'
  | 'variantStatus'
  | 'isActive'
  | 'isFeatured'
  | 'isCustomizable'
  | 'description'

export interface CatalogCsvRow {
  productId?: string
  sku?: string
  category: CatalogCategory
  occasionTags: CatalogCategory[]
  productType?: string
  collectionSeries?: string
  material: CatalogMaterial
  productName: string
  size: string
  price: number
  cost?: number
  pricingType: 'Fixed' | 'Starts From'
  orderType: 'Catalog' | 'Custom'
  variantStatus: CatalogVariantStatus
  isActive?: boolean
  isFeatured?: boolean
  isCustomizable?: boolean
  description?: string
  /** Optional columns that were actually present in the imported file. */
  providedFields: CatalogCsvOptionalField[]
}

export interface CsvParseError {
  row: number
  message: string
}

export interface CsvParseResult {
  rows: CatalogCsvRow[]
  errors: CsvParseError[]
}

const csvCell = (value: string | number | boolean): string => {
  const str = String(value)
  return /[",\n]/.test(str) ? `"${str.replace(/"/g, '""')}"` : str
}

/**
 * @description Builds a downloadable template for the current occasion list.
 * Optional shared fields are included so a round-trip export/import does not
 * discard Storefront metadata.
 */
export const buildCatalogCsvTemplate = (categoryNames: string[]): string => {
  const header = CSV_IMPORT_COLUMNS.join(',')
  const exampleRows = categoryNames.map((category, index) => {
    const material = index % 2 === 0 ? 'Fresh' : 'Artificial'
    return [
      '',
      '',
      `Example ${category}`,
      category,
      category,
      'Bouquet',
      'Medium',
      material,
      '',
      150000,
      '',
      'Fixed',
      'Catalog',
      'active',
      'Yes',
      'No',
      'No',
      '',
    ].map(csvCell).join(',')
  })
  return [header, ...exampleRows].join('\n')
}

const normalizeCategory = (
  value: string,
  validCategories: string[],
): CatalogCategory | undefined =>
  validCategories.find(
    (category) => category.toLowerCase() === value.trim().toLowerCase(),
  )

const normalizeMaterial = (value: string): CatalogMaterial | undefined => {
  const normalized = value.trim().toLowerCase()
  if (normalized === 'fresh') return 'fresh'
  if (normalized === 'artificial') return 'artificial'
  return undefined
}

const normalizePricingType = (value: string): 'Fixed' | 'Starts From' | undefined => {
  const normalized = value.trim().toLowerCase()
  if (!normalized) return 'Fixed'
  if (normalized === 'fixed') return 'Fixed'
  if (normalized === 'starts from' || normalized === 'start from' || normalized === 'starting from') return 'Starts From'
  return undefined
}

const normalizeOrderType = (value: string): 'Catalog' | 'Custom' | undefined => {
  const normalized = value.trim().toLowerCase()
  if (!normalized) return 'Catalog'
  if (normalized === 'catalog') return 'Catalog'
  if (normalized === 'custom') return 'Custom'
  return undefined
}

const normalizeVariantStatus = (value: string): CatalogVariantStatus | undefined => {
  const normalized = value.trim().toLowerCase()
  if (!normalized) return 'active'
  if (normalized === 'active') return 'active'
  if (normalized === 'inactive') return 'inactive'
  return undefined
}

const normalizeOptionalBoolean = (value: string): boolean | undefined | null => {
  const normalized = value.trim().toLowerCase()
  if (!normalized) return undefined
  if (['yes', 'true', '1', 'active'].includes(normalized)) return true
  if (['no', 'false', '0', 'inactive'].includes(normalized)) return false
  return null
}

/** Minimal CSV line parser with support for quoted commas and escaped quotes. */
const splitCsvLine = (line: string): string[] => {
  const cells: string[] = []
  let current = ''
  let quoted = false

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index]
    if (char === '"') {
      if (quoted && line[index + 1] === '"') {
        current += '"'
        index += 1
      } else {
        quoted = !quoted
      }
      continue
    }
    if (char === ',' && !quoted) {
      cells.push(current.trim())
      current = ''
      continue
    }
    current += char
  }

  cells.push(current.trim())
  return cells
}

const headerIndex = (header: string[], ...aliases: string[]): number => {
  for (const alias of aliases) {
    const index = header.indexOf(alias.toLowerCase())
    if (index >= 0) return index
  }
  return -1
}

const cellAt = (cells: string[], index: number): string =>
  index >= 0 ? (cells[index] ?? '').trim() : ''

const parseOccasionTags = (
  value: string,
  category: CatalogCategory,
  validCategories: string[],
): { tags: CatalogCategory[]; unknown: string[] } => {
  const rawTags = value
    .split(/[|;,]/)
    .map((tag) => tag.trim())
    .filter(Boolean)
  const tags: CatalogCategory[] = [category]
  const unknown: string[] = []

  for (const rawTag of rawTags) {
    const normalized = normalizeCategory(rawTag, validCategories)
    if (!normalized) unknown.push(rawTag)
    else tags.push(normalized)
  }

  return { tags: [...new Set(tags)], unknown }
}

/**
 * @description Parses raw CSV text. Legacy `Material` and `Product Type`
 * headers remain accepted as aliases for `Material Type` and `Arrangement Type`.
 */
export const parseCatalogCsv = (
  csvText: string,
  validCategories: string[],
): CsvParseResult => {
  const lines = csvText.split(/\r?\n/).filter((line) => line.trim().length > 0)
  if (lines.length === 0) return { rows: [], errors: [] }

  const header = splitCsvLine(lines[0]).map((cell) => cell.trim().toLowerCase())
  const colIndex = {
    productId: headerIndex(header, 'product id'),
    sku: headerIndex(header, 'sku'),
    productName: headerIndex(header, 'product name'),
    category: headerIndex(header, 'category', 'main occasion'),
    occasionTags: headerIndex(header, 'occasion tags', 'occasions'),
    productType: headerIndex(header, 'arrangement type', 'product type'),
    size: headerIndex(header, 'size'),
    material: headerIndex(header, 'material type', 'material'),
    collectionSeries: headerIndex(header, 'collection / series', 'collection/series', 'collection', 'series'),
    price: headerIndex(header, 'price'),
    cost: headerIndex(header, 'cost'),
    pricingType: headerIndex(header, 'pricing type'),
    orderType: headerIndex(header, 'order type'),
    variantStatus: headerIndex(header, 'variant status', 'status'),
    isActive: headerIndex(header, 'product active', 'active'),
    isFeatured: headerIndex(header, 'featured'),
    isCustomizable: headerIndex(header, 'customizable'),
    description: headerIndex(header, 'description'),
  }

  const requiredHeaders: Array<[number, string]> = [
    [colIndex.category, 'Category'],
    [colIndex.material, 'Material Type'],
    [colIndex.productName, 'Product Name'],
    [colIndex.size, 'Size'],
    [colIndex.price, 'Price'],
  ]
  const missingHeaders = requiredHeaders.filter(([index]) => index < 0).map(([, name]) => name)
  if (missingHeaders.length > 0) {
    return {
      rows: [],
      errors: [{ row: 1, message: `Missing required column${missingHeaders.length === 1 ? '' : 's'}: ${missingHeaders.join(', ')}` }],
    }
  }

  const rows: CatalogCsvRow[] = []
  const errors: CsvParseError[] = []

  for (let i = 1; i < lines.length; i += 1) {
    const rowNumber = i + 1
    const cells = splitCsvLine(lines[i])

    const rawCategory = cellAt(cells, colIndex.category)
    const rawMaterial = cellAt(cells, colIndex.material)
    const productName = cellAt(cells, colIndex.productName)
    const size = cellAt(cells, colIndex.size)
    const rawPrice = cellAt(cells, colIndex.price).replace(/[^0-9-]/g, '')
    const rawCost = cellAt(cells, colIndex.cost).replace(/[^0-9-]/g, '')

    const category = normalizeCategory(rawCategory, validCategories)
    const material = normalizeMaterial(rawMaterial)
    const price = rawPrice ? Number(rawPrice) : Number.NaN
    const cost = rawCost ? Number(rawCost) : undefined
    const pricingType = normalizePricingType(cellAt(cells, colIndex.pricingType))
    const orderType = normalizeOrderType(cellAt(cells, colIndex.orderType))
    const variantStatus = normalizeVariantStatus(cellAt(cells, colIndex.variantStatus))
    const isActive = normalizeOptionalBoolean(cellAt(cells, colIndex.isActive))
    const isFeatured = normalizeOptionalBoolean(cellAt(cells, colIndex.isFeatured))
    const isCustomizable = normalizeOptionalBoolean(cellAt(cells, colIndex.isCustomizable))

    if (!category) {
      errors.push({ row: rowNumber, message: `Unknown occasion "${rawCategory}" (expected one of: ${validCategories.join(', ')})` })
      continue
    }
    if (!material) {
      errors.push({ row: rowNumber, message: `Material Type must be "Fresh" or "Artificial", got "${rawMaterial}"` })
      continue
    }
    if (!productName) {
      errors.push({ row: rowNumber, message: 'Product Name is required' })
      continue
    }
    if (!size) {
      errors.push({ row: rowNumber, message: 'Size is required' })
      continue
    }
    if (!Number.isFinite(price) || price < 0) {
      errors.push({ row: rowNumber, message: `Invalid Price "${cellAt(cells, colIndex.price)}"` })
      continue
    }
    if (cost !== undefined && (!Number.isFinite(cost) || cost < 0)) {
      errors.push({ row: rowNumber, message: `Invalid Cost "${cellAt(cells, colIndex.cost)}"` })
      continue
    }
    if (!pricingType) {
      errors.push({ row: rowNumber, message: `Pricing Type must be "Fixed" or "Starts From"` })
      continue
    }
    if (!orderType) {
      errors.push({ row: rowNumber, message: `Order Type must be "Catalog" or "Custom"` })
      continue
    }
    if (!variantStatus) {
      errors.push({ row: rowNumber, message: `Variant Status must be "active" or "inactive"` })
      continue
    }
    if (isActive === null || isFeatured === null || isCustomizable === null) {
      errors.push({ row: rowNumber, message: 'Product Active, Featured, and Customizable must use Yes/No or True/False when supplied' })
      continue
    }

    const { tags, unknown } = parseOccasionTags(
      cellAt(cells, colIndex.occasionTags),
      category,
      validCategories,
    )
    if (unknown.length > 0) {
      errors.push({ row: rowNumber, message: `Unknown occasion tag${unknown.length === 1 ? '' : 's'}: ${unknown.join(', ')}` })
      continue
    }

    const providedFields: CatalogCsvOptionalField[] = []
    const optionalIndexes: Array<[CatalogCsvOptionalField, number]> = [
      ['productId', colIndex.productId],
      ['sku', colIndex.sku],
      ['occasionTags', colIndex.occasionTags],
      ['productType', colIndex.productType],
      ['collectionSeries', colIndex.collectionSeries],
      ['cost', colIndex.cost],
      ['pricingType', colIndex.pricingType],
      ['orderType', colIndex.orderType],
      ['variantStatus', colIndex.variantStatus],
      ['isActive', colIndex.isActive],
      ['isFeatured', colIndex.isFeatured],
      ['isCustomizable', colIndex.isCustomizable],
      ['description', colIndex.description],
    ]
    optionalIndexes.forEach(([field, index]) => { if (index >= 0) providedFields.push(field) })

    rows.push({
      productId: cellAt(cells, colIndex.productId) || undefined,
      sku: cellAt(cells, colIndex.sku) || undefined,
      category,
      occasionTags: tags,
      productType: cellAt(cells, colIndex.productType) || undefined,
      collectionSeries: cellAt(cells, colIndex.collectionSeries) || undefined,
      material,
      productName,
      size,
      price,
      cost,
      pricingType,
      orderType,
      variantStatus,
      isActive: isActive ?? undefined,
      isFeatured: isFeatured ?? undefined,
      isCustomizable: isCustomizable ?? undefined,
      description: cellAt(cells, colIndex.description) || undefined,
      providedFields,
    })
  }

  return { rows, errors }
}

/** Customer-facing name rule shared by form entry and CSV imports. */
export const buildCatalogDisplayName = (
  productName: string,
  collectionSeries?: string,
): string => {
  const name = productName.trim()
  const collection = collectionSeries?.trim()
  if (!collection) return name
  const prefix = `${collection} - `
  return name.toLowerCase().startsWith(prefix.toLowerCase())
    ? name
    : `${prefix}${name}`
}

/**
 * @description Legacy fallback key for matching a product when no stable
 * Product ID is supplied in an import row.
 */
export const productMatchKey = (
  category: CatalogCategory,
  material: CatalogMaterial,
  productName: string,
): string => `${category}::${material}::${productName.trim().toLowerCase()}`

/**
 * @description Exports the normalized shared Catalog fields. Thumbnail and
 * gallery are intentionally omitted because Phase 5 will move image content
 * to Supabase Storage rather than embedding it in CSV.
 */
export const exportCatalogCsv = (products: CatalogProduct[]): string => {
  const rows: string[] = [CSV_IMPORT_COLUMNS.join(',')]

  for (const product of products) {
    for (const variant of product.variants) {
      rows.push(
        [
          product.productId,
          variant.sku,
          product.name,
          product.category,
          (product.occasionTags?.length ? product.occasionTags : [product.category]).join(' | '),
          product.productType ?? '',
          variant.size,
          product.material === 'fresh' ? 'Fresh' : 'Artificial',
          product.collectionSeries ?? '',
          variant.price,
          variant.cost ?? '',
          product.pricingType ?? 'Fixed',
          product.orderType ?? 'Catalog',
          variant.status,
          product.isActive ? 'Yes' : 'No',
          product.isFeatured ? 'Yes' : 'No',
          product.isCustomizable ? 'Yes' : 'No',
          product.description ?? '',
        ]
          .map(csvCell)
          .join(','),
      )
    }
  }

  return rows.join('\n')
}
