import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(path, 'utf8')

describe('mobile workflow UI scale regressions', () => {
  it('keeps the top bar visually minimal and touch friendly', () => {
    const topBar = read('src/components/dashboard/TopBar.tsx')
    expect(topBar).toContain('bg-background/95')
    expect(topBar).toContain('bg-transparent text-foreground')
    expect(topBar).toContain('size-10 items-center justify-center rounded-full')
    expect(topBar).toContain('border border-border/80 bg-card')
    expect(topBar).toContain('md:grid-cols-[minmax(8.5rem,auto)_minmax(12rem,24rem)_auto]')
    expect(topBar).toContain('xl:grid-cols-[minmax(0,1fr)_minmax(20rem,42rem)_minmax(0,1fr)]')
    expect(topBar).not.toContain('bg-primary text-primary-foreground shadow-ios-sm')
  })

  it('keeps the iPad header compact without losing desktop search context', () => {
    const topBar = read('src/components/dashboard/TopBar.tsx')
    const home = read('src/pages/Home.tsx')

    expect(topBar).toContain('md:grid-cols-[minmax(8.5rem,auto)_minmax(12rem,24rem)_auto]')
    expect(topBar).toContain('className="hidden w-full md:block xl:hidden"')
    expect(topBar).toContain('tabletSearchPlaceholder ?? searchPlaceholder')
    expect(topBar).toContain('max-w-20 truncate lg:max-w-28 xl:max-w-40')
    expect(home).toContain("payroll: 'Search payroll…'")
    expect(home).toContain('tabletSearchPlaceholder={searchConfig.tabletPlaceholder}')
  })

  it('keeps branch menus portalled and Assign Florist single-scroll', () => {
    const topBar = read('src/components/dashboard/TopBar.tsx')
    const assign = read('src/components/orders/AssignFloristDialog.tsx')
    expect(topBar).toContain('createPortal')
    expect(topBar).toContain('fixed z-[120]')
    expect(assign).not.toContain('max-h-[46vh]')
    expect(assign).toContain('min-h-0 flex-1 overflow-y-auto')
    expect(assign).toContain('border-t border-border bg-surface-footer')
  })

  it('shares one order progress component and reduces Finance review actions', () => {
    const orderStepper = read('src/components/orders/OrderStatusStepper.tsx')
    const financeStepper = read('src/components/finance/OrderFinanceReviewSheetStepper.tsx')
    const footer = read('src/components/finance/OrderFinanceReviewSheetFooter.tsx')
    expect(orderStepper).toContain('OrderProgressStepper')
    expect(financeStepper).toContain('OrderProgressStepper')
    expect(footer).toContain('Needs correction')
    expect(footer).toContain('Send correction request')
    expect(footer).not.toContain('Reject order')
    expect(footer).not.toContain('>Close<')
  })

  it('uses shared centered and scrollable controls across Finance, People and Revenue', () => {
    const financeTabs = read('src/components/finance/FinanceWorkspaceTabs.tsx')
    const payroll = read('src/components/finance/FinancePayrollReview.tsx')
    const peopleTabs = read('src/components/hr/PeopleWorkspaceUI.tsx')
    const revenue = read('src/components/dashboard/RevenueDashboard.tsx')
    expect(financeTabs).toContain('rounded-xl border px-4 py-3 text-left')
    expect(financeTabs).toContain('min-h-[4.75rem]')
    expect(financeTabs).not.toContain('rounded-full')
    expect(payroll).toContain('settingsTabTrackClass')
    expect(payroll).toContain('settingsTabButtonClass')
    expect(payroll).toContain('PayrollStatusBadge')
    expect(peopleTabs).toContain('settingsTabButtonClass')
    expect(peopleTabs).toContain("level: 'primary'")
    expect(peopleTabs).toContain('PEOPLE_SECTION_META')
    expect(peopleTabs).toContain('Icon className="size-4 shrink-0"')
    expect(revenue).toContain('text-base font-semibold leading-6 text-foreground')
    expect(revenue).toContain('<ChipRow')
    expect(revenue).toContain('<FilterChip')
  })

  it('keeps Finance tabs contained, Notifications actions clear and People scheduling views functional', () => {
    const financeTabs = read('src/components/finance/FinanceWorkspaceTabs.tsx')
    const notifications = read('src/components/notifications/NotificationCenter.tsx')
    const people = read('src/components/hr/HrTabContent.tsx')
    const home = read('src/pages/Home.tsx')
    const scheduling = read('src/components/hr/HrSchedulingSection.tsx')

    expect(financeTabs).toContain('sm:[mask-image:none]')
    expect(financeTabs).toContain('sm:p-0')
    expect(financeTabs).toContain('truncate whitespace-nowrap')

    expect(notifications).toContain('hideCloseButton')
    expect(notifications).toContain('Close notifications')
    expect(notifications).toContain('sm:grid-cols-[minmax(0,1fr)_auto_auto]')
    expect(notifications).toContain('sm:col-start-2 sm:row-start-1')

    expect(home).toContain("scheduling: 'Search schedules by employee, branch, or shift…'")
    expect(home).toContain('searchQuery={searchQuery}')
    expect(people).not.toContain('peopleSearchPlaceholder')
    expect(scheduling).not.toContain('placeholder="Search employee"')
    expect(scheduling).toContain("mobileMode === 'week' ? 'block' : 'hidden'")
    expect(scheduling).toContain("mobileMode==='day'?'Grid':'Day'")
  })

  it('keeps desktop search singular and Catalog filter utilities compact', () => {
    const topBar = read('src/components/dashboard/TopBar.tsx')
    const catalog = read('src/components/catalog/CatalogFiltersBar.tsx')
    const orders = read('src/components/orders/OrdersTableFilters.tsx')

    expect(topBar).toContain('const TopBarSearch')
    expect(topBar).toContain('text-sm text-foreground outline-none transition')
    expect(topBar).not.toContain('text-sm shadow-sm outline-none')
    expect(catalog).not.toContain('<FiltersSearchInput')
    expect(orders).not.toContain('placeholder="Search orders')
    expect(catalog).toContain('min-w-[9rem]')
    expect(catalog).toContain('aria-label={`Sort products:')
    expect(catalog).toContain('[&>svg:last-child]:hidden')
    expect(catalog).toContain('border-b-2')
    expect(catalog).not.toContain('FilterChip')
  })

  it('keeps Reports, attendance, overview and Settings on the compact hierarchy', () => {
    const reports = read('src/components/hr/HrMonthlyReportSection.tsx')
    const warningReview = read('src/components/hr/AttendanceReviewQueue.tsx')
    const attendance = read('src/components/hr/HrTabContent.tsx')
    const dashboardHeader = read('src/components/dashboard/DashboardHeader.tsx')
    const settings = read('src/components/settings/SettingsCenter.tsx')
    const settingsPrimitives = read('src/components/settings/SettingsPrimitives.tsx')

    expect(reports).toContain("settingsTabTrackClass({ level:'primary'")
    expect(reports).toContain('<ChipRow activeKey={problemStatus}')
    expect(reports).toContain('No problems in this view')
    expect(warningReview).toContain('className="space-y-3"')
    expect(warningReview).not.toContain('space-y-4 rounded-xl bg-card p-4')
    expect(attendance).toContain('min-h-[68px]')
    expect(attendance).toContain('h-11 rounded-full border border-border bg-background px-4 text-sm')
    expect(dashboardHeader).toContain('w-fit items-center')
    expect(dashboardHeader).not.toContain('w-full items-center justify-center')
    expect(settings).toContain('Read-only</span>')
    expect(settings).toContain('mb-4 flex flex-col gap-2 border-b')
    expect(settingsPrimitives).toContain('flex size-9 shrink-0')
  })

  it('keeps the redesigned People desktop workspace compact and aligned', () => {
    const people = read('src/components/hr/PeopleWorkspaceUI.tsx')
    const periods = read('src/components/hr/PeoplePeriodControls.tsx')
    const points = read('src/components/hr/HrPointsSection.tsx')
    const payroll = read('src/components/hr/HrPayrollSection.tsx')
    const scheduling = read('src/components/hr/HrSchedulingSection.tsx')

    expect(people).toContain('PEOPLE_SECTION_META')
    expect(people).toContain('Icon className="size-4 shrink-0"')
    expect(people).toContain('flex size-10 shrink-0')
    expect(periods).toContain('max-w-[520px]')
    expect(points).toContain('aria-label="Point sections"')
    expect(points).toContain("settingsTabButtonClass({ active:view === item, level:'primary'")
    expect(points).not.toContain('rounded-full bg-surface-panel p-1')
    expect(payroll).toContain('border-y border-border/60 py-3')
    expect(payroll).toContain('md:justify-between')
    expect(scheduling).toContain('<PeoplePeriodNavigation')
    expect(scheduling).toContain('w-[1042px] min-w-[1042px]')
    const reports = read('src/components/hr/HrMonthlyReportSection.tsx')
    expect(reports).toContain('md:justify-between')
    expect(reports).toContain("'Branch split'")
    expect(reports).toContain("'Missing punches'")
    expect(reports).toContain('min-w-[1040px]')
  })

})
