/** Finance transaction verification, grouped history and filters. */
import { useMemo, useState, type FC } from 'react'
import { Calendar as CalendarIcon, ChevronDown, ChevronRight, ReceiptText, Search } from 'lucide-react'
import { format, subDays } from 'date-fns'
import type { DateRange } from 'react-day-picker'
import type { FinanceCategory, FinanceTransaction, FinanceTransactionType } from '../../store/financeStoreTypes'
import { useFinanceStore } from '../../store/financeStore'
import { getFinanceCategoryLabel, getCategoriesForDirection } from '../../domain/financeTransactionCategoryDomain'
import type { InternalTransactionVerificationQueueViewModel } from './InternalTransactionVerificationQueueController'
import { Popover, PopoverContent, PopoverTrigger } from '../ui/popover'
import { Calendar } from '../ui/calendar'
import { StatusChip } from '../ui/chip'

const formatIdr=(value:number)=>`Rp${value.toLocaleString('id-ID')}`
type PeriodFilter='today'|'7d'|'30d'|'custom'
type SourceTab='all'|'orders'|'payroll'|'refunds'|'manual'

export interface InternalTransactionVerificationQueueProps {
  transactions: FinanceTransaction[]
  canVerify: boolean
  actorName: string
  actorRole: import('../../store/userStore').UserRole
  defaultBranch?: import('../../types/orders').BranchFilter
}
const businessDate=(t:FinanceTransaction)=>(t.transactionDate??t.createdAt).slice(0,10)
const sourceMatches=(t:FinanceTransaction,tab:SourceTab)=>tab==='all'||(tab==='orders'&&t.source==='order_payment')||(tab==='payroll'&&t.source==='payroll')||(tab==='refunds'&&t.source==='order_refund')||(tab==='manual'&&(t.entryMode??(t.isSystemGenerated?'automatic':'manual'))==='manual')

const TransactionRow=({transaction,canVerify,onStartReject,onVerify}:{transaction:FinanceTransaction;canVerify?:boolean;onStartReject?:()=>void;onVerify?:()=>void})=>{
 const custom=useFinanceStore(s=>s.customCategories), overrides=useFinanceStore(s=>s.categoryOverrides)
 const scopeLabel=(transaction.scope??(transaction.branch==='All'?'company':'branch'))==='company'?'Company-wide':transaction.branch
 return <article className="rounded-xl border border-border/60 bg-card px-4 py-3">
  <div className="flex min-w-0 items-start justify-between gap-3 sm:gap-4"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{transaction.name??transaction.description}</p><p className="mt-1 text-xs text-muted-foreground">{getFinanceCategoryLabel(transaction.category,custom,overrides)} · {scopeLabel} · {transaction.method}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(transaction.transactionDate??transaction.createdAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}{transaction.entryMode==='automatic'?' · Automatic':''}</p></div><div className="shrink-0 text-right"><p className={`whitespace-nowrap text-sm font-semibold sm:text-base ${transaction.type==='income'?'text-success':'text-destructive'}`}>{transaction.type==='income'?'+':'−'}{formatIdr(transaction.amount)}</p><StatusChip tone={transaction.status==='verified'?'success':transaction.status==='rejected'?'destructive':'info'}>{transaction.status==='verified'?'Verified':transaction.status==='rejected'?'Rejected':'Pending'}</StatusChip></div></div>
  {transaction.manualEntryReason&&<p className="mt-2 rounded-lg bg-warning/10 px-3 py-2 text-xs text-warning">Manual automatic-category entry: {transaction.manualEntryReason}</p>}
  {transaction.dataWarning&&<p className="mt-2 rounded-lg bg-warning/10 px-3 py-2 text-xs font-medium text-warning">{transaction.dataWarning}</p>}
  {canVerify&&transaction.status==='pending'&&<div className="mt-3 flex justify-end gap-2 border-t border-border/50 pt-3"><button onClick={onStartReject} className="h-11 rounded-full border border-destructive/30 px-4 text-sm text-destructive">Reject</button><button onClick={onVerify} className="h-11 rounded-full bg-primary px-4 text-sm font-semibold text-primary-foreground">Verify</button></div>}
 </article>
}

const Group=({label,itemLabel,items,canVerify,actionTransactionId,actionType,onStartReject,onCloseAction,onVerify,onConfirmReject}:{label:string;itemLabel:string;items:FinanceTransaction[];canVerify:boolean;actionTransactionId?:string;actionType?:string;onStartReject:(id:string)=>void;onCloseAction:()=>void;onVerify:(id:string)=>void;onConfirmReject:(id:string)=>void})=>{
 const [open,setOpen]=useState(true); const total=items.reduce((s,t)=>s+(t.type==='income'?t.amount:-t.amount),0)
 return <section className="overflow-hidden rounded-xl border border-border/70 bg-card"><button type="button" onClick={()=>setOpen(v=>!v)} className="flex min-h-16 w-full min-w-0 items-center justify-between gap-3 px-4 py-3 text-left sm:gap-4"><span className="flex min-w-0 items-center gap-2">{open?<ChevronDown className="size-4"/>:<ChevronRight className="size-4"/>}<span className="min-w-0"><span className="block truncate font-semibold">{label}</span><span className="block truncate text-xs text-muted-foreground">{items.length} {itemLabel}</span></span></span><span className={`shrink-0 whitespace-nowrap text-sm font-semibold sm:text-base ${total>=0?'text-success':'text-destructive'}`}>{total>=0?'+':'−'}{formatIdr(Math.abs(total))}</span></button>{open&&<div className="space-y-2 border-t border-border/60 p-2">{items.map(t=><div key={t.id}><TransactionRow transaction={t} canVerify={canVerify&&!(actionTransactionId===t.id&&actionType==='reject')} onStartReject={()=>onStartReject(t.id)} onVerify={()=>onVerify(t.id)}/>{actionTransactionId===t.id&&actionType==='reject'&&<div className="mt-1 flex items-center gap-2 rounded-xl bg-destructive/5 p-3"><span className="mr-auto text-xs">Reject this transaction?</span><button onClick={onCloseAction} className="h-11 rounded-full px-4">Back</button><button onClick={()=>onConfirmReject(t.id)} className="h-11 rounded-full bg-destructive px-4 text-white">Confirm reject</button></div>}</div>)}</div>}</section>
}

export const InternalTransactionVerificationQueue: FC<InternalTransactionVerificationQueueViewModel>=({canVerify,isVisible,actionTransactionId,actionType,pendingTransactions,verifiedTransactions,rejectedTransactions,defaultBranch,onStartReject,onCloseAction,onVerify,onConfirmReject})=>{
 const custom=useFinanceStore(s=>s.customCategories), overrides=useFinanceStore(s=>s.categoryOverrides)
 const [sourceTab,setSourceTab]=useState<SourceTab>('all'), [search,setSearch]=useState(''), [direction,setDirection]=useState<'all'|FinanceTransactionType>('all'), [category,setCategory]=useState<'all'|FinanceCategory>('all'), [method,setMethod]=useState<'all'|FinanceTransaction['method']>('all'), [branch,setBranch]=useState<string>(defaultBranch??'All'), [period,setPeriod]=useState<PeriodFilter>('30d'), [range,setRange]=useState<DateRange|undefined>(), [customOpen,setCustomOpen]=useState(false)
 const all=useMemo(()=>[...pendingTransactions,...verifiedTransactions,...rejectedTransactions],[pendingTransactions,verifiedTransactions,rejectedTransactions])
 const branchNames=useMemo(()=>Array.from(new Set(all.filter(t=>(t.scope??(t.branch==='All'?'company':'branch'))==='branch').map(t=>t.branch))).sort(),[all])
 const availableCategories=useMemo(()=>direction==='all'?Array.from(new Set(all.map(t=>t.category))):Array.from(new Set(all.map(t=>t.category))).filter(id=>new Set(getCategoriesForDirection(direction,custom,overrides).map(d=>d.id)).has(id)),[all,direction,custom,overrides])
 const today=new Date();today.setHours(0,0,0,0);const bounds=period==='today'?{from:today,to:today}:period==='7d'?{from:subDays(today,6),to:today}:period==='30d'?{from:subDays(today,29),to:today}:range;const from=bounds?.from?format(bounds.from,'yyyy-MM-dd'):'';const to=bounds?.to?format(bounds.to,'yyyy-MM-dd'):''
 const filter=(items:FinanceTransaction[])=>items.filter(t=>{const d=businessDate(t);const scope=t.scope??(t.branch==='All'?'company':'branch');const query=search.trim().toLowerCase();const searchable=[t.name,t.description,t.orderNumber,t.groupLabel,t.reference,t.branch,getFinanceCategoryLabel(t.category,custom,overrides)].filter(Boolean).join(' ').toLowerCase();return sourceMatches(t,sourceTab)&&(!query||searchable.includes(query))&&(direction==='all'||t.type===direction)&&(category==='all'||t.category===category)&&(method==='all'||t.method===method)&&(branch==='All'||(branch==='Company-wide'?scope==='company':scope==='branch'&&t.branch===branch))&&(!from||d>=from)&&(!to||d<=to)})
 const visible=[...filter(pendingTransactions),...filter(verifiedTransactions),...filter(rejectedTransactions)].sort((a,b)=>businessDate(b).localeCompare(businessDate(a)))
 const groups=useMemo(()=>{const map=new Map<string,FinanceTransaction[]>();for(const t of visible){let key;if(t.groupType==='payroll_cycle'){key=`payroll:${t.groupKey??t.payrollPeriodId}`}else if(t.groupType==='source_batch'){key=`batch:${t.groupKey??t.id}`}else if((t.entryMode??(t.isSystemGenerated?'automatic':'manual'))==='manual'){key=`manual:${t.id}`}else{key=`${t.source??'automatic'}:${businessDate(t)}`}map.set(key,[...(map.get(key)??[]),t])}return [...map.entries()].map(([key,items])=>{const first=items[0];const label=first.groupType==='payroll_cycle'?`Payroll · ${first.groupLabel??first.payrollPeriodId}`:first.groupType==='source_batch'?(first.groupLabel??'Automatic batch'):first.entryMode==='manual'?(first.name??first.description):new Date(`${businessDate(first)}T12:00:00`).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'});const itemLabel=first.source==='order_payment'?`completed order${items.length===1?'':'s'}`:first.source==='order_refund'?`completed refund${items.length===1?'':'s'}`:first.source==='payroll'?`payroll entr${items.length===1?'y':'ies'}`:`transaction${items.length===1?'':'s'}`;return {key,label,itemLabel,items}})},[visible])
 if(!isVisible)return null
 return <section className="space-y-5" aria-label="Transaction verification"><header><h2 className="text-lg font-semibold">Transactions</h2><p className="text-sm text-muted-foreground">Automatic and manual Money In / Money Out records, grouped by business date or period.</p></header>
  <div className="no-scrollbar flex gap-1 overflow-x-auto border-b border-border">{([['all','All'],['orders','Orders'],['payroll','Payroll'],['refunds','Refunds'],['manual','Manual']] as const).map(([v,l])=><button key={v} onClick={()=>setSourceTab(v)} className={`h-11 shrink-0 border-b-2 px-4 text-sm font-medium ${sourceTab===v?'border-foreground text-foreground':'border-transparent text-muted-foreground'}`}>{l}</button>)}</div>
  <div className="space-y-3 rounded-xl border border-border/70 bg-card p-4"><label className="relative block"><Search className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input aria-label="Search transactions" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search transaction, order, branch, or category" className="h-11 w-full rounded-full border border-border bg-background pl-11 pr-4 text-sm outline-none focus:ring-2 focus:ring-primary/20"/></label><div className="flex flex-wrap gap-2"><div className="inline-flex rounded-full bg-surface-track p-1">{(['all','income','expense'] as const).map(v=><button key={v} onClick={()=>{setDirection(v);setCategory('all')}} className={`h-9 rounded-full px-3.5 text-sm ${direction===v?'bg-primary text-primary-foreground':'text-muted-foreground'}`}>{v==='all'?'All':v==='income'?'In':'Out'}</button>)}</div><div className="flex rounded-full bg-surface-track p-1">{(['today','7d','30d'] as const).map(v=><button key={v} onClick={()=>setPeriod(v)} className={`h-9 rounded-full px-3.5 text-sm ${period===v?'bg-card shadow-sm':'text-muted-foreground'}`}>{v==='today'?'Today':v.toUpperCase()}</button>)}<Popover open={customOpen} onOpenChange={setCustomOpen}><PopoverTrigger asChild><button onClick={()=>setPeriod('custom')} className={`inline-flex h-9 items-center gap-1 rounded-full px-3.5 text-sm ${period==='custom'?'bg-card shadow-sm':'text-muted-foreground'}`}><CalendarIcon className="size-3.5"/>Custom</button></PopoverTrigger><PopoverContent className="w-[21rem] p-3"><Calendar mode="range" selected={range} onSelect={r=>{setRange(r);setPeriod('custom');if(r?.from&&r.to)setCustomOpen(false)}}/></PopoverContent></Popover></div></div>
  <div className="grid gap-2 sm:grid-cols-3"><select value={category} onChange={e=>setCategory(e.target.value as 'all'|FinanceCategory)} className="h-11 rounded-full border border-border px-3"><option value="all">All categories</option>{availableCategories.map(id=><option key={id} value={id}>{getFinanceCategoryLabel(id,custom,overrides)}</option>)}</select><select value={method} onChange={e=>setMethod(e.target.value as typeof method)} className="h-11 rounded-full border border-border px-3"><option value="all">All payment methods</option><option value="cash">Cash</option><option value="transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select><select value={branch} onChange={e=>setBranch(e.target.value)} className="h-11 rounded-full border border-border px-3"><option value="All">All</option><option value="Company-wide">Company-wide</option>{branchNames.map(b=><option key={b} value={b}>{b}</option>)}</select></div></div>
  {groups.length===0?<div className="flex min-h-36 flex-col items-center justify-center rounded-xl border border-dashed border-border"><ReceiptText className="size-5 text-muted-foreground"/><p className="mt-2 font-semibold">No transactions in this view</p></div>:<div className="space-y-3">{groups.map(g=><Group key={g.key} label={g.label} itemLabel={g.itemLabel} items={g.items} canVerify={canVerify} actionTransactionId={actionTransactionId ?? undefined} actionType={actionType ?? undefined} onStartReject={onStartReject} onCloseAction={onCloseAction} onVerify={onVerify} onConfirmReject={onConfirmReject}/>)}</div>}
 </section>
}
